<?php 
$PROJECT_MODE='PROD';
$PROJECT_NAME='KalyanaVeena.com';
$PROJECT_PROTOCOL=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']==='on'?"https":"http");
$PROJECT_HOST = $_SERVER['HTTP_HOST'];
if($PROJECT_HOST=='localhost'){ $PROJECT_MODE='DEBUG'; } 
$PROJECT_URL = $PROJECT_PROTOCOL."://".$PROJECT_HOST;
if($PROJECT_MODE=='DEBUG'){ $PROJECT_URL = 'http://localhost/ws'; }
$PROJECT_PAYLOGO = 'http://localhost/KalynVna/website/images/logo-square.png';
?>
<script type="text/javascript">
var PROJECT_MODE = '<?php if(isset($_SESSION["PROJECT_MODE"])) { echo $_SESSION["PROJECT_MODE"]; } ?>';
var PROJECT_URL = '<?php if(isset($_SESSION["PROJECT_URL"])) { echo $_SESSION["PROJECT_URL"]; } ?>';
/* ACCOUNTS: */
var AUTH_USER_LOGIN = '<?php if(isset($_SESSION["AUTH_USER_LOGIN"])) { echo $_SESSION["AUTH_USER_LOGIN"]; } ?>';
var ACCOUNT_TYPE = '<?php if(isset($_SESSION["ACCOUNT_TYPE"])) { echo $_SESSION["ACCOUNT_TYPE"]; } ?>';
/* ACCOUNT_TYPE: (ADMINISTRATOR) */
var ADMIN_ACCOUNT_ID = '<?php if(isset($_SESSION["ADMIN_ACCOUNT_ID"])) { echo $_SESSION["ADMIN_ACCOUNT_ID"];  } ?>';
var ADMIN_ACCOUNT_SURNAME = '<?php if(isset($_SESSION["ADMIN_ACCOUNT_SURNAME"])) { echo $_SESSION["ADMIN_ACCOUNT_SURNAME"]; } ?>';
var ADMIN_ACCOUNT_NAME = '<?php if(isset($_SESSION["ADMIN_ACCOUNT_NAME"])) { echo $_SESSION["ADMIN_ACCOUNT_NAME"]; } ?>';
var ADMIN_ACCOUNT_EMAIL = '<?php if(isset($_SESSION["ADMIN_ACCOUNT_EMAIL"])) { echo $_SESSION["ADMIN_ACCOUNT_EMAIL"]; } ?>';
var ADMIN_ACCOUNT_PWD = '<?php if(isset($_SESSION["ADMIN_ACCOUNT_PWD"])) { echo $_SESSION["ADMIN_ACCOUNT_PWD"]; } ?>';
var ADMIN_ACCOUNT_CREATEDON = '<?php if(isset($_SESSION["ADMIN_ACCOUNT_CREATEDON"])) { echo $_SESSION["ADMIN_ACCOUNT_CREATEDON"]; } ?>'
/* ACCOUNT_TYPE: (CUSTOMER) */
var CUSTOMERACCOUNT_MOBCODE = '<?php if(isset($_SESSION["CUSTOMERACCOUNT_MOBCODE"])){ echo $_SESSION["CUSTOMERACCOUNT_MOBCODE"]; } ?>';
var CUSTOMERACCOUNT_MOBILE = '<?php if(isset($_SESSION["CUSTOMERACCOUNT_MOBILE"])){ echo $_SESSION["CUSTOMERACCOUNT_MOBILE"];} ?>';
var CUSTOMERACCOUNT_SURNAME = '<?php if(isset($_SESSION["CUSTOMERACCOUNT_SURNAME"])){ echo $_SESSION["CUSTOMERACCOUNT_SURNAME"];} ?>';
var CUSTOMERACCOUNT_NAME = '<?php if(isset($_SESSION["CUSTOMERACCOUNT_NAME"])){ echo $_SESSION["CUSTOMERACCOUNT_NAME"];} ?>';
var CUSTOMERACCOUNT_PROFILES = '<?php if(isset($_SESSION["CUSTOMERACCOUNT_PROFILES"])){ echo $_SESSION["CUSTOMERACCOUNT_PROFILES"]; }  ?>';
var CUSTOMERACCOUNT_BALANCE = '<?php if(isset($_SESSION["CUSTOMERACCOUNT_BALANCE"])){ echo $_SESSION["CUSTOMERACCOUNT_BALANCE"]; }  ?>';

console.log("PROJECT_URL: "+PROJECT_URL);
console.log("CUSTOMERACCOUNT_MOBCODE: "+CUSTOMERACCOUNT_MOBCODE);
console.log("CUSTOMERACCOUNT_MOBILE: "+CUSTOMERACCOUNT_MOBILE);
console.log("CUSTOMERACCOUNT_SURNAME: "+CUSTOMERACCOUNT_SURNAME);
console.log("CUSTOMERACCOUNT_NAME: "+CUSTOMERACCOUNT_NAME);
console.log("CUSTOMERACCOUNT_PROFILES: "+CUSTOMERACCOUNT_PROFILES);
console.log("CUSTOMERACCOUNT_BALANCE: "+CUSTOMERACCOUNT_BALANCE);
</script>